unique_ids:
  forms:
    applications: AGSVABV4NWJMDLW6MFBM7VJ2GFLVKZG6
    applications.RowTemplate2: HRYEDJ5BKDIEDZVN2SCJHWVESN3JREHS
    systems_and_accounts: TK6TVW3HEYSWP7XIAODF47MPZG6RYG6B
    systems_and_accounts.RowTemplate1: J3KRYVGXYQZFUJP4XG6OJRCARP2I7EE5
  modules: {}
  server_modules:
    ServerModule1: IAAQYXFJZOFSDTYJTD6O5WIKKN3GOGCN
  assets:
    standard-page.html: NXTMVKOL7H72PBJU5TW246DNPAYJFT2O
    theme.css: U2ULY4PT4N74YF4XA2NBBEA5EMZ2EOSY
