unique_ids:
  forms:
    systems_and_accounts: TK6TVW3HEYSWP7XIAODF47MPZG6RYG6B
    applications: AGSVABV4NWJMDLW6MFBM7VJ2GFLVKZG6
    Application_Area_Summary: TVDF3CDEPYLMEEIXN4CFUYPMPWQWMFGQ
    Application_Area_Summary.RowTemplate3_copy: TBXPFASJD3PXJ5WFLBDKQ2HDEVX3SF4E
    systems_and_accounts.RowTemplate1: J3KRYVGXYQZFUJP4XG6OJRCARP2I7EE5
    RowTemplate4: KWTJQ5A6EYJQRCPTXR2CIE4OOCF3K6PG
    applications.RowTemplate2: 7VSN277DVND3FZ5B5UYQKTAUBATMJDBQ
    Application_Area_Summary.RowTemplate3: JJ7WS27KAD5K4GMFU3SWL5HX3M42EKKA
    Pivot: 2GHFO6TAQWTBG3G3MSWKRGSB6AOPZYAT
  modules: {}
  server_modules:
    ServerModule1: IAAQYXFJZOFSDTYJTD6O5WIKKN3GOGCN
  assets:
    jqueryUI.js: VOI4YHF7JXVMR3UQKGRI5SRRULMMLLCT
    standard-page.html: NXTMVKOL7H72PBJU5TW246DNPAYJFT2O
    theme.css: U2ULY4PT4N74YF4XA2NBBEA5EMZ2EOSY
